spring:
  application:
    name: todo-app
  datasource:
    url: jdbc:postgresql://localhost:5432/todo_db
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false