server:
  port: 8082

spring:
  application:
    name: stats-service
  datasource:
    url: jdbc:postgresql://localhost:5432/todo_db
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.default_schema: stats
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:29092}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml